mass = float(input('enter mass in kg:'))
acceleration = float(input('enter acceleration in m/s^2:'))
velocity = float(input('enter velocity in m/s^2:'))
gravity = 10
distance = float(input('distance in m:'))
height = float(input('height in m:'))
initialvelocity = float(input('initialvelocity in m/s:'))
time = float(input('time in s:'))
force = mass*acceleration
potentialenergy = mass*gravity*height
finalvelocity = initialvelocity+acceleration*time
kineticenergy = 1/2*mass*velocity**2
velocity = distance/time
print('The force is =', force)
print('The kineticenergy is = ', kineticenergy)
print('the velocity is = : ', velocity)
print('the potential-energy is =:', potentialenergy)
print('The finalvelocity is =:', finalvelocity)